apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
      - name: abc-tech-container
        image: abc-tech:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
