
    # Install dependencies for Prometheus and Grafana
    - name: Update apt and install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    # Install Prometheus
    - name: Add Prometheus GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Prometheus APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    # Install Grafana
    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    # Enable and start Prometheus and Grafana services
    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

    - name: Enable and start Grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    # Open firewall for Prometheus and Grafana
#    - name: Allow Prometheus and Grafana through firewall
#      ufw:
#        rule: allow
#        name: "{{ item }}"
#      loop:
#        - '3000'  # Grafana
#        - '9090'  # Prometheus
